### PR TITLE
reemkufi: v0.007 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/alif-type/reem-kufi

---
## FontBakery Report:
```There is a total of 126 checks on <Section: Default>.
Start ... running 126 individual check executions.
>> com.google.fonts/check/018 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Checking OS/2 achVendID.
 * WARN: OS/2 VendorID value 'ALIF' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

   Result: WARN

>> com.google.fonts/check/019 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Substitute copyright, registered and trademark symbols in name table entries.
 * FAIL: NAMEID #0 contains symbol that should be replaced by '(c)'.

   Result: FAIL

>> com.google.fonts/check/032 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Description strings in the name table must not exceed 100 characters.
 * FAIL: Namerecords with ID=10 (NAMEID_DESCRIPTION) are longer than 100 characters and should be removed.

   Result: FAIL

>> com.google.fonts/check/045 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Does the font have a DSIG table?
 * FAIL: This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly.

   Result: FAIL

>> com.google.fonts/check/046 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Font contains the first few mandatory glyphs (.null or NULL, CR and space)?
 * WARN: Font is missing glyphs for the following mandatory codepoints: 0x0000, 0x000D.

   Result: WARN

>> com.google.fonts/check/055 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Version format is correct in 'name' table?
 * FAIL: The NAMEID_VERSION_STRING (nameID=5) value must follow the pattern "Version X.Y" with X.Y between 1.000 and 9.999. Current version string is: "Version 0.007" [code: bad-version-strings]

   Result: FAIL

>> com.google.fonts/check/062 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Is GASP table correctly set?
 * FAIL: Font is missing the GASP table. Try exporting the font with autohinting enabled.

   Result: FAIL

>> com.google.fonts/check/064 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Is there a caret position declared for every ligature?
 * WARN: This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

   Result: WARN

>> com.google.fonts/check/065 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Is there kerning info for non-ligated sequences?
 * ERROR: Failed with KeyError: 'uni0066'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 307, in _exec_check_generator
             for sub_result in gen:
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 2591, in com_google_fonts_check_065
             look_for_nonligated_kern_info(lookup)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 2571, in look_for_nonligated_kern_info
             if pairvalue.SecondGlyph in ligatures[glyph]:
         KeyError: 'uni0066'
         

   Result: ERROR

>> com.google.fonts/check/072 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Font enables smart dropout control in "prep" table instructions?
 * WARN: Font does not contain TrueType instructions enabling smart dropout control in the 'prep' table program. Please try exporting the font with autohinting enabled.

   Result: WARN

>> com.google.fonts/check/074 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Are there non-ASCII characters in ASCII-only NAME table entries?
 * FAIL: There are 1 strings containing non-ASCII characters in the ASCII-only NAME table entries.

   Result: FAIL

>> com.google.fonts/check/075 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Check for points out of bounds.
 * WARN: The following glyphs have coordinates which are out of bounds:
[('uni1ECD', 295.02404, -150.29868999999997), ('uni1ECD', 275.6867, -150.29868999999997), ('uni1ECD', 256.34936, -150.29868999999997), ('uni1ECB', 149.02404, -150.29868999999997), ('uni1ECB', 129.6867, -150.29868999999997), ('uni1ECB', 110.34936, -150.29868999999997), ('uni1EC7', 284.02404, -150.29868999999997), ('uni1EC7', 264.6867, -150.29868999999997), ('uni1EC7', 245.34936, -150.29868999999997), ('uni1EC4', 239.59743, 1137.44552), ('uni1EC4', 272.99829, 1137.44552), ('uni1EC4', 298.48842, 1137.44552), ('uni1EC4', 441.76053, 1137.44552), ('uni1EC4', 497.13564, 1137.44552), ('uni1EC5', 174.59743, 830.44552), ('uni1EC5', 207.99829, 830.44552), ('uni1EC5', 233.48842000000002, 830.44552), ('uni1EC5', 376.76053, 830.44552), ('uni1EC5', 432.13564, 830.44552), ('uni013E', 379, 735), ('uni00C3', 257.59743000000003, 960.44552), ('uni00C3', 290.99829, 960.44552), ('uni00C3', 316.48842, 960.44552), ('uni00C3', 459.76053, 960.44552), ('uni00C3', 515.13564, 960.44552), ('uni00F1', 187.59743, 608.44552), ('uni00F1', 220.99829, 608.44552), ('uni00F1', 246.48842000000002, 608.44552), ('uni00F1', 389.76053, 608.44552), ('uni00F1', 445.13564, 608.44552), ('uni0303', 304.11761, 459.93135), ('uni0303', 270.71675000000005, 459.93135), ('uni0303', 123.04979, 459.93135), ('uni0303', 67.67468, 459.93135), ('uni0303', 133.59743, 601.44552), ('uni0303', 166.99829, 601.44552), ('uni0303', 192.48842000000002, 601.44552), ('uni0303', 335.76053, 601.44552), ('uni0303', 391.13564, 601.44552), ('uni0303', 331.36568, 459.93135), ('uni201D', 279, 693), ('uni201E', 279, 50), ('uni00D1', 314.59743000000003, 932.44552), ('uni00D1', 347.99829, 932.44552), ('uni00D1', 373.48842, 932.44552), ('uni00D1', 516.76053, 932.44552), ('uni00D1', 572.13564, 932.44552), ('uni00D5', 335.59743000000003, 939.44552), ('uni00D5', 368.99829, 939.44552), ('uni00D5', 394.48842, 939.44552), ('uni00D5', 537.76053, 939.44552), ('uni00D5', 593.13564, 939.44552), ('uni1ED7', 178.59743, 830.44552), ('uni1ED7', 211.99829, 830.44552), ('uni1ED7', 237.48842000000002, 830.44552), ('uni1ED7', 380.76053, 830.44552), ('uni1ED7', 436.13564, 830.44552), ('uni1ED6', 331.59743000000003, 1130.44552), ('uni1ED6', 364.99829, 1130.44552), ('uni1ED6', 390.48842, 1130.44552), ('uni1ED6', 533.76053, 1130.44552), ('uni1ED6', 589.13564, 1130.44552), ('uni1ED9', 295.02404, -150.29868999999997), ('uni1ED9', 275.6867, -150.29868999999997), ('uni1ED9', 256.34936, -150.29868999999997), ('uni0303.case', 314.11761, 735.9313500000001), ('uni0303.case', 280.71675000000005, 735.9313500000001), ('uni0303.case', 133.04979, 735.9313500000001), ('uni0303.case', 77.67468, 735.9313500000001), ('uni0303.case', 143.59743, 877.44552), ('uni0303.case', 176.99829, 877.44552), ('uni0303.case', 202.48842000000002, 877.44552), ('uni0303.case', 345.76053, 877.44552), ('uni0303.case', 401.13564, 877.44552), ('uni0303.case', 341.36568, 735.9313500000001), ('uni1EAD', 316.02404, -150.29868999999997), ('uni1EAD', 296.6867, -150.29868999999997), ('uni1EAD', 277.34936, -150.29868999999997), ('uni0168', 275.59743000000003, 946.44552), ('uni0168', 308.99829, 946.44552), ('uni0168', 334.48842, 946.44552), ('uni0168', 477.76053, 946.44552), ('uni0168', 533.13564, 946.44552), ('uni0169', 185.59743, 615.44552), ('uni0169', 218.99829, 615.44552), ('uni0169', 244.48842000000002, 615.44552), ('uni0169', 387.76053, 615.44552), ('uni0169', 443.13564, 615.44552), ('uni1EAB', 212.59743, 830.44552), ('uni1EAB', 245.99829, 830.44552), ('uni1EAB', 271.48842, 830.44552), ('uni1EAB', 414.76053, 830.44552), ('uni1EAB', 470.13564, 830.44552), ('uni1EA1', 316.02404, -150.29868999999997), ('uni1EA1', 296.6867, -150.29868999999997), ('uni1EA1', 277.34936, -150.29868999999997), ('uni00E3', 217.59743, 615.44552), ('uni00E3', 250.99829, 615.44552), ('uni00E3', 276.48842, 615.44552), ('uni00E3', 419.76053, 615.44552), ('uni00E3', 475.13564, 615.44552), ('uni1EEE', 275.59743000000003, 946.44552), ('uni1EEE', 308.99829, 946.44552), ('uni1EEE', 334.48842, 946.44552), ('uni1EEE', 477.76053, 946.44552), ('uni1EEE', 533.13564, 946.44552), ('uni1EEF', 185.59743, 615.44552), ('uni1EEF', 218.99829, 615.44552), ('uni1EEF', 244.48842000000002, 615.44552), ('uni1EEF', 387.76053, 615.44552), ('uni1EEF', 443.13564, 615.44552), ('uni1EB9', 284.02404, -150.29868999999997), ('uni1EB9', 264.6867, -150.29868999999997), ('uni1EB9', 245.34936, -150.29868999999997), ('uni1EE0', 335.59743000000003, 939.44552), ('uni1EE0', 368.99829, 939.44552), ('uni1EE0', 394.48842, 939.44552), ('uni1EE0', 537.76053, 939.44552), ('uni1EE0', 593.13564, 939.44552), ('uni1EE3', 295.02404, -150.29868999999997), ('uni1EE3', 275.6867, -150.29868999999997), ('uni1EE3', 256.34936, -150.29868999999997), ('uni1EE5', 297.02404, -150.29868999999997), ('uni1EE5', 277.6867, -150.29868999999997), ('uni1EE5', 258.34936, -150.29868999999997), ('uni1EB5', 226.59743, 833.44552), ('uni1EB5', 259.99829, 833.44552), ('uni1EB5', 285.48842, 833.44552), ('uni1EB5', 428.76053, 833.44552), ('uni1EB5', 484.13564, 833.44552), ('uni0323', 59.82747, -101.95533999999998), ('uni0323', 59.82747, -81.73902999999996), ('uni0323', 92.34936, -53.61198999999999), ('uni0323', 111.6867, -53.61198999999999), ('uni0323', 131.02404, -53.61198999999999), ('uni0323', 131.02404, -150.29868999999997), ('uni0323', 111.6867, -150.29868999999997), ('uni0323', 92.34936, -150.29868999999997), ('uni0323', 59.82747, -123.92958999999996), ('uni1EAA', 253.59743, 1150.44552), ('uni1EAA', 286.99829, 1150.44552), ('uni1EAA', 312.48842, 1150.44552), ('uni1EAA', 455.76053, 1150.44552), ('uni1EAA', 511.13564, 1150.44552), ('uni03020303', 143.59743, 822.44552), ('uni03020303', 176.99829, 822.44552), ('uni03020303', 202.48842000000002, 822.44552), ('uni03020303', 345.76053, 822.44552), ('uni03020303', 401.13564, 822.44552), ('uni1EB4', 256.59743000000003, 1179.44552), ('uni1EB4', 289.99829, 1179.44552), ('uni1EB4', 315.48842, 1179.44552), ('uni1EB4', 458.76053, 1179.44552), ('uni1EB4', 514.13564, 1179.44552), ('uni1EB7', 316.02404, -150.29868999999997), ('uni1EB7', 296.6867, -150.29868999999997), ('uni1EB7', 277.34936, -150.29868999999997), ('uni010F', 711, 742), ('uni1EBC', 244.59743, 946.44552), ('uni1EBC', 277.99829, 946.44552), ('uni1EBC', 303.48842, 946.44552), ('uni1EBC', 446.76053, 946.44552), ('uni1EBC', 502.13564, 946.44552), ('uni1EBD', 180.59743, 616.44552), ('uni1EBD', 213.99829, 616.44552), ('uni1EBD', 239.48842000000002, 616.44552), ('uni1EBD', 382.76053, 616.44552), ('uni1EBD', 438.13564, 616.44552), ('uni00F5', 183.59743, 615.44552), ('uni00F5', 216.99829, 615.44552), ('uni00F5', 242.48842000000002, 615.44552), ('uni00F5', 385.76053, 615.44552), ('uni00F5', 441.13564, 615.44552), ('uni1EF9', 165.59743, 601.44552), ('uni1EF9', 198.99829, 601.44552), ('uni1EF9', 224.48842000000002, 601.44552), ('uni1EF9', 367.76053, 601.44552), ('uni1EF9', 423.13564, 601.44552), ('uni1EF8', 269.59743000000003, 944.44552), ('uni1EF8', 302.99829, 944.44552), ('uni1EF8', 328.48842, 944.44552), ('uni1EF8', 471.76053, 944.44552), ('uni1EF8', 527.13564, 944.44552), ('uni1EF1', 297.02404, -150.29868999999997), ('uni1EF1', 277.6867, -150.29868999999997), ('uni1EF1', 258.34936, -150.29868999999997), ('uni03060303', 136.59743, 831.44552), ('uni03060303', 169.99829, 831.44552), ('uni03060303', 195.48842000000002, 831.44552), ('uni03060303', 338.76053, 831.44552), ('uni03060303', 394.13564, 831.44552), ('uni0128', 63.59743, 946.44552), ('uni0128', 96.99829, 946.44552), ('uni0128', 122.48842000000002, 946.44552), ('uni0128', 265.76053, 946.44552), ('uni0128', 321.13564, 946.44552), ('uni0129', 39.59743, 601.44552), ('uni0129', 72.99829, 601.44552), ('uni0129', 98.48842000000002, 601.44552), ('uni0129', 241.76053000000002, 601.44552), ('uni0129', 297.13564, 601.44552)]
This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message

   Result: WARN

>> com.google.fonts/check/153 with ((u'font[0]', '/Users/marc/Downloads/ReemKufi-0.7/ttf/ReemKufi-Regular.ttf'),)
   Check if each glyph has the recommended amount of contours.
 * WARN: This check inspects the glyph outlines and detects the total number of counters in each of them. The expected values are infered from the typical ammounts of counters observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni20A4	Counters detected: 2	Expected: 1
Glyph name: uni00D0	Counters detected: 3	Expected: 2
Glyph name: uni0110	Counters detected: 3	Expected: 2
Glyph name: uni0111	Counters detected: 3	Expected: 2
Glyph name: uni0127	Counters detected: 2	Expected: 1
Glyph name: uni0166	Counters detected: 2	Expected: 1
Glyph name: uni0167	Counters detected: 2	Expected: 1
Glyph name: uni01A1	Counters detected: 3	Expected: 2
Glyph name: uni01AF	Counters detected: 2	Expected: 1
Glyph name: uni01B0	Counters detected: 2	Expected: 1
Glyph name: uni1EDB	Counters detected: 4	Expected: 3
Glyph name: uni1EDD	Counters detected: 4	Expected: 3
Glyph name: uni1EDF	Counters detected: 4	Expected: 3
Glyph name: uni1EE1	Counters detected: 4	Expected: 3
Glyph name: uni1EE3	Counters detected: 4	Expected: 3
Glyph name: uni1EE8	Counters detected: 3	Expected: 2
Glyph name: uni1EE9	Counters detected: 3	Expected: 2
Glyph name: uni1EEA	Counters detected: 3	Expected: 2
Glyph name: uni1EEB	Counters detected: 3	Expected: 2
Glyph name: uni1EEC	Counters detected: 3	Expected: 2
Glyph name: uni1EED	Counters detected: 3	Expected: 2
Glyph name: uni1EEE	Counters detected: 3	Expected: 2
Glyph name: uni1EEF	Counters detected: 3	Expected: 2
Glyph name: uni1EF0	Counters detected: 3	Expected: 2
Glyph name: uni1EF1	Counters detected: 3	Expected: 2

   Result: WARN

======== <Section: Default> ========
126 checks in section


Section results:

    ERROR: 1
    FAIL: 6
    WARN: 6
    SKIP: 48
    INFO: 5
    PASS: 60

======== END <Section: Default> ========

Total:

    ERROR: 1
    FAIL: 6
    WARN: 6
    SKIP: 48
    INFO: 5
    PASS: 60


DONE!

```

---
## DiffBrowsers Report:
```Regression Report:

Fonts: ["ReemKufi-Regular"]

View: glyphs-modified
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 7757 pixels

View: glyphs-missing
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same

View: glyphs-new
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 240212 pixels

View: waterfall
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 168142 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 167056 pixels
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 159680 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 152973 pixels
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 114050 pixels
WARNING: Google_Nexus_5_android_5.0_Android_Browser_.jpg is different by 17281 pixels

View: glyphs-all_26pt
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 31483 pixels
```

alt text

alt text

alt text

alt text

alt text

**Imgs**
https://drive.google.com/file/d/1x0gvae4jf2GP-5u1v_pdRXesZbF6fvKG/view?usp=drivesdk

**GFR**
http://www.gf-regression.com/compare/8ad2c6e0-013e-4920-abd0-0892bdd1eeab

### CODE REVIEW

**Comment by khaledhosny** [comment]
Do I need to fix any of these issues? (some look rather bogus to me, the others I need to further check).

**Comment by khaledhosny** [comment]
The changes to Latin comes from the updated Josefin Sans and because I know use the whole Latin font not just a subset of it.

**Comment by m4rc1e** [comment]
@khaledhosny Only thing that sticks out to me is the lack of a dummy DSIG table. Older ms apps depend on this.

Ignore the gasp, copyright string etc. I'm questioning these tests over at FB.

**Comment by khaledhosny** [comment]
DSIG is not needed for Arabic, it is needed only for Latin AFAIK, so it shouldn’t be a fatal error IMHO. Also I’m using fontmake, which does not seem to have a way to generate dummy DSIG.

**Comment by m4rc1e** [comment]
@khaledhosny issue posted https://github.com/googlefonts/fontbakery/issues/1845.

Sorry I've highjacked your family to help us improve our specs/qa tools :-)

**Pull request closed without merging**
